const privacy = () =>{
    return(
        <div className='privacy'>
            <div className='additionalHelp'>
                    <h2>ADDITIONAL HELP</h2>
                    <a href='#' className='contactUs'>CONTACT US</a>
            </div>
                    <h2>Terms & Conditions</h2>
                    <h2>Contests Rules & Terms</h2>
                    <p>
                    <em>Entry:</em> No purchase necessary to participate or win. A purchase will not improve one's chance of winning. 
                    Void where prohibited by the law of the state of the entrant. All federal, state, and local taxes may apply 
                    to any winnings. In order to participate in the promotion, You must have an account on Instagram  on which the 
                    Giveaway is being conducted, unless You choose to enter using an alternative method of entry. 
                    Entries submitted contrary to the Giveaway rules will be deemed void. All entries must include the information 
                    requested by Sponsors to be eligible. Only one prize per person, email address or username will be allowed per 
                    Giveaway. In the event of a dispute as to any entry or the identity of an entrant, entries will be declared to be 
                    made by the authorized account holder and natural person assigned by an Internet access provider to the e-mail 
                    address associated with the entry, and he/she must comply with these Official Rules. Entrants may be required to 
                    show proof of being the authorized account holder. All entries must be received within the time period stated by 
                    Sponsors in the Giveaway Posting to be eligible to win a prize. Late and/or subsequent entries not be eligible. 
                    Entries from one Giveaway will not be included in other giveaways. Entries generated by script, macro or other 
                    automated means, or by any means which subvert the entry process are void. All entries become the property of a 
                    Sponsor on whose social media 
                    account the entry was made and will not be acknowledged or returned.
                    </p>
                    <h2>Accessibility Statement</h2>
                    <p><b>We Value Digital Inclusion</b><br></br>
                    In our effort to provide a fully accessible and optimized user experience for all site visitors, Windsor Fashions has 
                    taken careful measure to ensure an excellent user experience, regardless of the assistive technology being used to 
                    access this site or the specific abilities of those individuals seeking access to this site.
                    The Windsor Fashions website is monitored and tested regularly by internal resources and by AudioEye, a third-party 
                    provider of Web Accessibility testing and monitoring. As issues of accessibility are identified, results of automated 
                    and manual testing are managed through the AudioEye® Digital Accessibility Platform. As new solutions are discovered to 
                    improve the user experience, 
                    remediation is tracked through the AudioEye system and fixes are implemented to improve the website user experience.
                    </p>
                    <h2>CUSTOMER INFORMATION POLICY</h2>
                    <p>
                    MJAY does not intend, and the site is not designed to collect personal information from those users under the age 
                    of 13. If you are under 13 years old, you should not provide personal information to our site or in connection with 
                    the services. Windsor recognizes that it must maintain and use customer information responsibly. The information 
                    collected is used to help us respond to customer inquiries, send emails about sales and events, and other marketing 
                    and promotional materials through the mail, contact contest winners and/or ship and bill orders. The information 
                    also helps us in determining what products appeal to our customers so we can better merchandise our site.
                    MJAY collects personal information necessary to process an order, a contest entry or a request to receive 
                    promotional emails from the consumer. This information includes name, address, city, state, zip code, phone number, 
                    email address, gender optional and date of birth optional. For those users who have opted to register their 
                    personal profile with the Site by setting up an account, the above information, including additional Ship To 
                    addresses, can be reviewed and maintained by the customer by accessing it through the My Account link in the top 
                    navigation bar of the Sites pages. For those customers who have not registered a maintainable account on the site, 
                    they may contact MJAY customer service at info@mjaystore.com to have their information updated as needed.
                    We may use customer information for marketing and promotional purposes. Each promotional email we send comes with a 
                    link that enables our customers to unsubscribe or remove themselves from our mailing list. In addition, we may from 
                    time to time make customer information available to other carefully screened companies. Categories of companies with 
                    which we may share information include other companies that we believe offer products and services that our 
                    customers may be interested in, either directly or through companies that market information about potential 
                    customers to other suppliers of products or services. If you would like to make sure that we make every effort not 
                    to share your email address or other information with third parties, just send an email message to 
                    info@mjaystore.com.

When we offer contests or promotions, or join with other companies to do so, visitors who choose to participate in these contests and promotions may be asked to provide personal information to participate. That information may then be used by us and any company offering the contest or promotions to notify winners or to fulfill promotional obligations. We may use third parties to perform services such as mailing marketing and promotional materials on our behalf. We will supply customer information to those third parties to the extent necessary to enable them to perform the services we have engaged them to provide.


                    </p>
</div>
    )
}
export default privacy